### ISSUE TITLE
Refactor the workflow

### ISSUE THREAD

**Issue by Xuanwo** [datafuselabs/databend-perf#34]
Current logic:

- Pull benchmark data from s3 in github actions
- Push data to the `main` branch
- Push transformed data to the `gh-pages` branch
- Frontend will be built to `gh-pages` either

With the power of vercel, we can improve the workflow to

- Pull benchmark data from s3 in github actions
- Push data to the `main` branch
- Build front and transfer data in vercel

Notes:

- We can do the json transform inside vite, so that we don't need to introduce golang here.
- Every time new data pushed or frontend changes, vercel will deploy a new version.

**Comment by Xuanwo** [comment]
@PsiACE @Chasen-Zhang fro review.

**Comment by PsiACE** [comment]
Makes sense.

**Comment by Chasen-Zhang** [comment]
> * We can do the json transform inside vite, so that we don't need to introduce golang here.

I still expect Golang to generate data and have the benefit of decoupling,  Convenient later maintenance and add some functions

**Comment by Xuanwo** [comment]
> I still expect Golang to generate data and have the benefit of decoupling, Convenient later maintenance and add some functions

It's more natural to transform the data in js directly. Or, how about let's play with rust wasm :smile:

**Comment by zqxul** [comment]
At first, golang was used only because I was better at using it

**Comment by Xuanwo** [comment]
The current workflow works and works well, let's keep it as-is.
