### ISSUE TITLE
Mobile view broken

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend-perf#37]
![A6904FF3-5D35-4AB9-BA9E-5930C9D42A1A](https://user-images.githubusercontent.com/172204/162450760-d8b20d26-809c-47d5-a25e-9b8592d9c577.jpeg)

**Comment by BohuTANG** [comment]
By the way, the sql text font uses a small size maybe better?

**Comment by Chasen-Zhang** [comment]
It hasn't been adapted for mobile, I'm going to make an issue

**Comment by Chasen-Zhang** [comment]
update in #39
